api = "0.10"

[build]
exclude = [
  "README.md"
]

[[build.env]]
name = "BP_NODE_RUN_SCRIPTS"
value = "build"

[[build.env]]
name = "NODE_ENV"
value = "production"

[[stacks]]
id="heroku-buildpack-nodejs"
